export const dummyProperties = [
  {
    id: 1,
    unitName: "Ocean Villa",
    unitType: "Landed House",
    rentingType: "By Rooms",
    location: "Ayer Keroh, Melaka",
    sizeSqft: 200,
    floorLevel: 2,
    status: "Available",
    address: "No 40, Jalan Bota, Taman Hijau, 75450 Melaka",
    city: "Ayer Keroh",
    state: "Melaka",
    postcode: 71050,
    totalBathroom: 3,
    facilities: [
      "Swimming pool",
      "Gym",
      "Free WiFi",
      "Parking lot",
      "Air conditioning",
      "Security guard",
      "BBQ area",
    ],
    photo: [
      "https://images.pexels.com/photos/1546168/pexels-photo-1546168.jpeg?cs=srgb&dl=pexels-david-mcbee-1546168.jpg&fm=jpg",
    ],
    rooms: [
      {
        id: 101,
        roomNo: "101-A",
        floorLevel: 3,
        roomType: "Master Bedroom",
        totalBeds: 3,
        size: 60,
        status: "Available",
      },
      {
        id: 102,
        roomNo: "101-B",
        floorLevel: 1,
        roomType: "Single Room",
        totalBeds: 1,
        size: 30,
        status: "Occupied",
      },
      {
        id: 103,
        roomNo: "101-C",
        floorLevel: 2,
        roomType: "Twin Sharing",
        totalBeds: 2,
        size: 40,
        status: "Renovation",
      },
      {
        id: 104,
        roomNo: "101-D",
        floorLevel: 4,
        roomType: "Small Room",
        totalBeds: 1,
        size: 10,
        status: "Inactive",
      },
    ],
  },
  {
    id: 2,
    unitName: "Sunset Heights",
    unitType: "Condominium",
    rentingType: "Whole Unit",
    location: "Cyberjaya, Selangor",
    sizeSqft: 850,
    floorLevel: 12,
    status: "Available",
    address: "Block A, Jalan Multimedia, 63000 Cyberjaya",
    city: "Cyberjaya",
    state: "Selangor",
    postcode: 63000,
    totalBathroom: 2,
    facilities: ["Gym", "Swimming pool", "Playground", "24h Security", "Sauna"],
    photo: [
      "https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?cs=srgb&dl=pexels-pixabay-259588.jpg&fm=jpg",
    ],
    rooms: [
      {
        id: 201,
        roomNo: "12-01",
        floorLevel: 12,
        roomType: "Master Room",
        totalBeds: 1,
        size: 120,
        status: "Occupied",
      },
      {
        id: 202,
        roomNo: "12-02",
        floorLevel: 12,
        roomType: "Single Room",
        totalBeds: 1,
        size: 80,
        status: "Occupied",
      },
    ],
  },
  {
    id: 3,
    unitName: "GreenView Apartment",
    unitType: "Apartment",
    rentingType: "By Rooms",
    location: "Johor Bahru, Johor",
    sizeSqft: 650,
    floorLevel: 8,
    status: "Available",
    address: "No 99, Jalan Meranti, Taman Puteri, 81200 Johor Bahru",
    city: "Johor Bahru",
    state: "Johor",
    postcode: 81200,
    totalBathroom: 2,
    facilities: ["Parking", "Elevator", "24h Security"],
    photo: [
      "https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?cs=srgb&dl=pexels-pixabay-323780.jpg&fm=jpg",
    ],
    rooms: [
      {
        id: 301,
        roomNo: "8-01",
        floorLevel: 8,
        roomType: "Single Room",
        totalBeds: 1,
        size: 50,
        status: "Available",
      },
      {
        id: 302,
        roomNo: "8-02",
        floorLevel: 8,
        roomType: "Twin Sharing",
        totalBeds: 2,
        size: 70,
        status: "Available",
      },
      {
        id: 303,
        roomNo: "8-03",
        floorLevel: 8,
        roomType: "Small Room",
        totalBeds: 1,
        size: 40,
        status: "Inactive",
      },
    ],
  },
  {
    id: 4,
    unitName: "The Pines Residences",
    unitType: "Service Apartment",
    rentingType: "Whole Unit",
    location: "Kota Kinabalu, Sabah",
    sizeSqft: 980,
    floorLevel: 20,
    status: "Available",
    address: "Tower 3, Jalan Sutera, 88300 Kota Kinabalu",
    city: "Kota Kinabalu",
    state: "Sabah",
    postcode: 88300,
    totalBathroom: 2,
    facilities: ["Gym", "Infinity Pool", "Security", "Cafe"],
    photo: [
      "https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?cs=srgb&dl=pexels-pixabay-106399.jpg&fm=jpg",
    ],
    rooms: [
      {
        id: 401,
        roomNo: "20-01",
        floorLevel: 20,
        roomType: "Master Room",
        totalBeds: 1,
        size: 150,
        status: "Available",
      },
      {
        id: 402,
        roomNo: "20-02",
        floorLevel: 20,
        roomType: "Guest Room",
        totalBeds: 1,
        size: 100,
        status: "Available",
      },
    ],
  },
  {
    id: 5,
    unitName: "Serene LakeHouse",
    unitType: "Landed Bungalow",
    rentingType: "Whole Unit",
    location: "Gelang Patah, Johor",
    sizeSqft: 3500,
    floorLevel: 2,
    status: "Available",
    address: "No 12, Jalan Tasik Biru, 81500 Gelang Patah",
    city: "Gelang Patah",
    state: "Johor",
    postcode: 81500,
    totalBathroom: 4,
    facilities: ["Private Garden", "Garage", "Security"],
    photo: [
      "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?cs=srgb&dl=pexels-vecislavas-popa-1571460.jpg&fm=jpg",
    ],
    rooms: [
      {
        id: 501,
        roomNo: "A1",
        floorLevel: 1,
        roomType: "Master Bedroom",
        totalBeds: 1,
        size: 200,
        status: "Available",
      },
      {
        id: 502,
        roomNo: "A2",
        floorLevel: 1,
        roomType: "Guest Room",
        totalBeds: 1,
        size: 150,
        status: "Available",
      },
      {
        id: 503,
        roomNo: "A3",
        floorLevel: 2,
        roomType: "Kids Room",
        totalBeds: 2,
        size: 120,
        status: "Available",
      },
    ],
  },
  {
    id: 6,
    unitName: "CityView Tower",
    unitType: "Condominium",
    rentingType: "By Rooms",
    location: "Kuala Lumpur",
    sizeSqft: 1100,
    floorLevel: 30,
    status: "Rented",
    address: "Tower B, Jalan Ampang, 50450 Kuala Lumpur",
    city: "Kuala Lumpur",
    state: "Kuala Lumpur",
    postcode: 50450,
    totalBathroom: 3,
    facilities: ["Gym", "Swimming Pool", "Sky Deck", "Security"],
    photo: [
      "https://images.pexels.com/photos/323705/pexels-photo-323705.jpeg?cs=srgb&dl=pexels-pixabay-323705.jpg&fm=jpg",
    ],
    rooms: [
      {
        id: 601,
        roomNo: "30-A",
        floorLevel: 30,
        roomType: "Master Room",
        totalBeds: 1,
        size: 130,
        status: "Occupied",
      },
      {
        id: 602,
        roomNo: "30-B",
        floorLevel: 30,
        roomType: "Medium Room",
        totalBeds: 1,
        size: 100,
        status: "Occupied",
      },
      {
        id: 603,
        roomNo: "30-C",
        floorLevel: 30,
        roomType: "Small Room",
        totalBeds: 1,
        size: 70,
        status: "Occupied",
      },
    ],
  },
  {
    id: 7,
    unitName: "Harmony Suites",
    unitType: "Service Apartment",
    rentingType: "By Rooms",
    location: "Penang Island",
    sizeSqft: 720,
    floorLevel: 15,
    status: "Available",
    address: "Block C, Jalan Kelawai, 10250 George Town",
    city: "George Town",
    state: "Penang",
    postcode: 10250,
    totalBathroom: 2,
    facilities: ["Gym", "Pool", "Lounge", "Security"],
    photo: [
      "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?cs=srgb&dl=pexels-mark-mccammon-1643383.jpg&fm=jpg",
    ],
    rooms: [
      {
        id: 701,
        roomNo: "15-01",
        floorLevel: 15,
        roomType: "Master Room",
        totalBeds: 1,
        size: 110,
        status: "Available",
      },
      {
        id: 702,
        roomNo: "15-02",
        floorLevel: 15,
        roomType: "Single Room",
        totalBeds: 1,
        size: 70,
        status: "Available",
      },
    ],
  },
  {
    id: 8,
    unitName: "Bukit Indah Residence",
    unitType: "Terrace House",
    rentingType: "Whole Unit",
    location: "Shah Alam, Selangor",
    sizeSqft: 1800,
    floorLevel: 2,
    status: "Available",
    address: "No 22, Jalan Bunga Raya, 40000 Shah Alam",
    city: "Shah Alam",
    state: "Selangor",
    postcode: 40000,
    totalBathroom: 3,
    facilities: ["Garage", "Playground", "Security"],
    photo: [
      "https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg?cs=srgb&dl=pexels-christa-grover-1457842.jpg&fm=jpg",
    ],
    rooms: [
      {
        id: 801,
        roomNo: "G1",
        floorLevel: 1,
        roomType: "Master Room",
        totalBeds: 1,
        size: 140,
        status: "Available",
      },
      {
        id: 802,
        roomNo: "G2",
        floorLevel: 2,
        roomType: "Guest Room",
        totalBeds: 1,
        size: 110,
        status: "Available",
      },
      {
        id: 803,
        roomNo: "G3",
        floorLevel: 2,
        roomType: "Kids Room",
        totalBeds: 2,
        size: 90,
        status: "Available",
      },
    ],
  },
  {
    id: 9,
    unitName: "Skyline Loft",
    unitType: "Penthouse",
    rentingType: "Whole Unit",
    location: "Mont Kiara, Kuala Lumpur",
    sizeSqft: 2300,
    floorLevel: 45,
    status: "Available",
    address: "Block A, Mont Kiara Residency, 50480 Kuala Lumpur",
    city: "Mont Kiara",
    state: "Kuala Lumpur",
    postcode: 50480,
    totalBathroom: 3,
    facilities: ["Private Lift", "Rooftop Access", "Gym", "Pool"],
    photo: [
      "https://images.pexels.com/photos/32870/pexels-photo.jpg?cs=srgb&dl=pexels-pixabay-32870.jpg&fm=jpg",
    ],
    rooms: [
      {
        id: 901,
        roomNo: "PH-1",
        floorLevel: 45,
        roomType: "Master Suite",
        totalBeds: 1,
        size: 300,
        status: "Available",
      },
      {
        id: 902,
        roomNo: "PH-2",
        floorLevel: 45,
        roomType: "Guest Suite",
        totalBeds: 1,
        size: 200,
        status: "Available",
      },
    ],
  },
  {
    id: 10,
    unitName: "Lakefront Condo",
    unitType: "Condominium",
    rentingType: "By Rooms",
    location: "Putrajaya",
    sizeSqft: 900,
    floorLevel: 18,
    status: "Available",
    address: "No 101, Presint 11, Putrajaya",
    city: "Putrajaya",
    state: "Putrajaya",
    postcode: 62000,
    totalBathroom: 2,
    facilities: ["Gym", "Pool", "Security", "Playground"],
    photo: [
      "https://images.pexels.com/photos/323705/pexels-photo-323705.jpeg?cs=srgb&dl=pexels-pixabay-323705.jpg&fm=jpg",
    ],
    rooms: [
      {
        id: 1001,
        roomNo: "18-A",
        floorLevel: 18,
        roomType: "Master Room",
        totalBeds: 1,
        size: 120,
        status: "Available",
      },
      {
        id: 1002,
        roomNo: "18-B",
        floorLevel: 18,
        roomType: "Single Room",
        totalBeds: 1,
        size: 80,
        status: "Available",
      },
      {
        id: 1003,
        roomNo: "18-C",
        floorLevel: 18,
        roomType: "Small Room",
        totalBeds: 1,
        size: 60,
        status: "Renovation",
      },
    ],
  },
];
